before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: q7zsTcqLg/R2lSzJpKdGoCencegPu26QmYWL2fB1ubh7Wlmri7uny7bTe0oCfNnH06qibBQ1Rm953f6oVH8SsVfT4lKTq5jBUh8SKiXH9Pg3z9VOZ5ghq9e7xgsrix+YID0fjhRq2F/7Dmtc79SBDQxoe1GfTnxH4g+CE3Qxduv+K1hG3WZSpyVRfCfNHWZe2mY6I1A+RgvGv4GYxhV03MWlwnTK28Eh0ZlluEhUhvBDdzxY7AJCqFjnML4aNhY8am4HMICuPAjhpuFP4hK0fLs5J42LhCVpt6mo6jvYWnYoSVre/G5B1tvK8+J6U9OUcAdDqkYGs2rjH52VvSOrjJJvvy9CTR/VFFOEF0ngeC00M2nK5dAhpTiG8wrVUMTyCPOJDXjEPqAnKBEpBDI/UP+wiAsoNTOC+4FNcs/uf9bEauQY3ppt9Q6JtAgPIoJEZXgHt1lnGn1oNBkV3J0Wk0pp1H+BoXXnnjMSMfMzOmLzS1A4R2ho0CsXr/flPfW6mz5IL9LIbxcm/uat7GSXyvG0K7hBUXBvg6+k1qCKQOCx2p+eS0ShszLqx0NGxt+Qa+LxAjlZj4YLrosb3g51zZNNhF6rrFHqCd/h3wS/WHr8SPjRo8YRZ1Mf9+Hr0OQlALSFPBGKZGnnCmEnjjEOcBlhUEF80q24p1FupLYTiAM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
